export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

// reducers for getting the current logged in user's orders
export const ORDER_LOGGED_IN_USER_REQUEST = 'ORDER_LOGGED_IN_USER_REQUEST';
export const ORDER_LOGGED_IN_USER_SUCCESS = 'ORDER_LOGGED_IN_USER_SUCCESS';
export const ORDER_LOGGED_IN_USER_FAIL = 'ORDER_LOGGED_IN_USER_FAIL';
export const ORDER_LOGGED_IN_USER_RESET = 'ORDER_LOGGED_IN_USER_RESET';
